version: '3.7'
services:
  db:
    platform: linux/amd64
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: midjourney
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - backend
volumes:
  mysql:
    driver: local

networks:
  backend:
    driver: bridge
